define(["backbone"],function(Backbone){
	var Router = Backbone.Router.extend({
		routes:{
			"":"home",
			home:"home",
			supermarket:"supermarket",
			shoppingCart:"shoppingCart",
			mine:"mine",
			search:"search",
			21743:"seckill",
			collect_com:"collect_com",
			collect_sto:"collect_sto",
			myOrder:"myOrder",
			integral:"integral",
			coupon:"coupon"
		},
		home:function(){
			require(["modules/home/home.js"],function(home){
				home.init();
			});
		},
		supermarket:function(){
			require(["modules/supermarket/supermarket.js"],function(supermarket){
				supermarket.init();
			});
		},
		shoppingCart:function(){
			require(["modules/shoppingCart/shoppingCart.js"],function(shoppingCart){
				shoppingCart.init();
			});
		},
		mine:function(){
			require(["modules/mine/mine.js"],function(mine){
				mine.init();
			})
		},
		search:function(){
			require(["modules/search/search.js"],function(search){
				search.init();
			});
		},
		seckill:function(){
			require(["modules/seckill/seckill.js"],function(seckill){
				seckill.init();
			});
		},
		collect_com:function(){
			require(["modules/collect_com/collect_com.js"],function(collect_com){
				collect_com.init();
			});
		},
		collect_sto:function(){
			require(["modules/collect_sto/collect_sto.js"],function(collect_sto){
				collect_sto.init();
			});
		},
		myOrder:function(){
			require(["modules/myOrder/myOrder.js"],function(myOrder){
				myOrder.init();
			})
		},
		integral:function(){
			require(["modules/integral/integral.js"],function(integral){
				integral.init();
			});
		},
		coupon:function(){
			require(["modules/coupon/coupon.js"],function(coupon){
				coupon.init();
			})
		}
	});
	return new Router();
});